# Generated by Django 5.1.4 on 2024-12-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datemanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebonustable',
            options={'managed': False},
        ),
    ]
