# Generated by Django 5.1.3 on 2024-12-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positiontable',
            fields=[
                ('positionname', models.CharField(db_column='PositionName', max_length=100, primary_key=True, serialize=False)),
                ('basesalary', models.DecimalField(db_column='BaseSalary', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'positiontable',
                'managed': False,
            },
        ),
    ]
