# Generated by Django 5.1.3 on 2024-12-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfor', '0002_positiontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeepositiontable',
            fields=[
                ('employeeid', models.OneToOneField(db_column='EmployeeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='basicinfor.employeetable')),
            ],
            options={
                'db_table': 'employeepositiontable',
                'managed': False,
            },
        ),
    ]
