# Generated by Django 5.1.3 on 2024-12-12 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendancetable',
            fields=[
                ('recordid', models.AutoField(db_column='RecordID', primary_key=True, serialize=False)),
                ('clockintime', models.TimeField(blank=True, db_column='ClockInTime', null=True)),
                ('clockouttime', models.TimeField(blank=True, db_column='ClockOutTime', null=True)),
            ],
            options={
                'db_table': 'attendancetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bonustable',
            fields=[
                ('bonusid', models.AutoField(db_column='BonusID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateField(db_column='PaymentDate')),
                ('reason', models.TextField(blank=True, db_column='Reason', null=True)),
            ],
            options={
                'db_table': 'bonustable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeebonustable',
            fields=[
                ('employeeid', models.IntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateField(db_column='PaymentDate')),
                ('reason', models.TextField(blank=True, db_column='Reason', null=True)),
            ],
            options={
                'db_table': 'employeebonustable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeetable',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('gender', models.CharField(db_column='Gender', max_length=6)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=20, null=True)),
            ],
            options={
                'db_table': 'employeetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performanceevaluationtable',
            fields=[
                ('employeeid', models.IntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('score', models.DecimalField(db_column='Score', decimal_places=2, max_digits=5)),
                ('evaluationdate', models.DateField(db_column='EvaluationDate')),
            ],
            options={
                'db_table': 'performanceevaluationtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performancetable',
            fields=[
                ('indicatorname', models.CharField(db_column='IndicatorName', max_length=100, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(db_column='Weight', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'performancetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positiontable',
            fields=[
                ('positionname', models.CharField(db_column='PositionName', max_length=100, primary_key=True, serialize=False)),
                ('basesalary', models.DecimalField(db_column='BaseSalary', decimal_places=2, max_digits=10, unique=True)),
            ],
            options={
                'db_table': 'positiontable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Socialsecurityandhousingfundtable',
            fields=[
                ('projectname', models.CharField(db_column='ProjectName', max_length=100, primary_key=True, serialize=False)),
                ('contributionrate', models.DecimalField(db_column='ContributionRate', decimal_places=2, max_digits=5, unique=True)),
            ],
            options={
                'db_table': 'socialsecurityandhousingfundtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxtable',
            fields=[
                ('taxname', models.CharField(db_column='TaxName', max_length=100, primary_key=True, serialize=False)),
                ('lowerlimit', models.DecimalField(db_column='LowerLimit', decimal_places=2, max_digits=10)),
                ('upperlimit', models.DecimalField(db_column='UpperLimit', decimal_places=2, max_digits=10)),
                ('taxrate', models.DecimalField(db_column='TaxRate', decimal_places=2, max_digits=5)),
                ('quickdeduction', models.DecimalField(db_column='QuickDeduction', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'taxtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workdaytable',
            fields=[
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
                ('isworkday', models.IntegerField(db_column='IsWorkday')),
            ],
            options={
                'db_table': 'workdaytable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeepositiontable',
            fields=[
                ('employeeid', models.OneToOneField(db_column='EmployeeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='salary.employeetable')),
            ],
            options={
                'db_table': 'employeepositiontable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeesocialsecurityandhousingfundtable',
            fields=[
                ('employeeid', models.OneToOneField(db_column='EmployeeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='salary.employeetable')),
                ('amountdue', models.DecimalField(blank=True, db_column='AmountDue', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'employeesocialsecurityandhousingfundtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeetaxtable',
            fields=[
                ('employeeid', models.OneToOneField(db_column='EmployeeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='salary.employeetable')),
                ('taxamount', models.DecimalField(db_column='TaxAmount', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'employeetaxtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grosssalary',
            fields=[
                ('employeeid', models.OneToOneField(db_column='EmployeeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='salary.employeetable')),
                ('year', models.IntegerField(db_column='Year')),
                ('month', models.IntegerField(db_column='Month')),
                ('absentdeduction', models.DecimalField(blank=True, db_column='AbsentDeduction', decimal_places=2, max_digits=10, null=True)),
                ('overtimepay', models.DecimalField(blank=True, db_column='OvertimePay', decimal_places=2, max_digits=10, null=True)),
                ('performancebonus', models.DecimalField(blank=True, db_column='PerformanceBonus', decimal_places=2, max_digits=10, null=True)),
                ('yearendbonus', models.DecimalField(blank=True, db_column='YearEndBonus', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'grosssalary',
                'managed': False,
            },
        ),
    ]
